INSERT INTO maps (owner_id, title, description)
VALUES (1, 'Unicorn forests', 'These are the forests where you can find unicorns.'),
(1, 'Dog Parks', 'Best dog parks in town for a ruff time.'),
(1, 'Best Bakeries', 'These are the top 5 bakeries in Vancouver.'),
(2, 'Best Benches', 'The best benches you can find in Vancouver.'),
(2, 'Best Sushi', 'The freshest and most authentic sushi you can find in Vanouver.'),
(3, 'Bars in Vancouver', 'List of all the bars I have been in Vancouver.'),
(3, 'Independent Liquor Stores', 'List of all the independent liquor stores in Vancouver.'),
(3, 'Used Car Dealerships', 'These are the best car dealerships to find prices for used cars.'),
(4, 'Best hair salons', 'The best hair salons in Vancouver.'),
(4, 'Best nail salons', 'Best nail salons in Vancouver where you will never get cut.'),
(5, 'Furniture Stores', 'List of all the furniture shops in Vancouver.'),
(5, 'Mattress stores', 'All of the places where you can buy a mattress in Vancouver.'),
(6, 'Biggest Playgrounds', 'Biggest playgrounds for the kiddos.'),
(6, 'Beaches in Vancouver', 'Best beaches in Vancouver, listed from most private to least private.'),
(7, 'Thrift Shops', 'List of all the best thrift stores in Vancouver.'),
(7, 'Unique Bars', 'The prettiest bars in Vancouver'),
(8, 'Tire shops', 'Where to get your tires changed in Vancouver.'),
(9, 'Best pie shop', 'List of the best pie shops in Vancouver.'),
(9, 'Pumpkin Patches', 'List of the patches you can visit this fall.'),
(10, 'Favourite cat cafes', 'The best places to get a cup of a coffee for the most obvious reasons.');
